### Swap two rows ###
**Description**<br>
Given m and n, swap the mth and nth rows of the 2-D NumPy array given below.
<br>
`
a = [[4 3 1]
     [5 7 0]
     [9 9 3]
     [8 2 4]]
`<br>
Example:<br>
Input 1:<br>
`0
2`<br>
Output 1:<br>
`
[[9 9 3] 
 [5 7 0] 
 [4 3 1] 
 [8 2 4]] 
 `

In [7]:
import numpy as np 

# Given array
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

# Read the values of m and n
import sys
lines = sys.stdin.readlines()
m = int(input()) #int(lines[0])
n = int(input()) #int(lines[1])

# Write your code for swapping here
a[m], a[n] = a[n], a[m]
# Print the array after swapping
print(a)


0
0
[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]


### Create border array ###<br>
**Description**<br>
Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.<br>
<br>
Note: Make sure the array is of type int.<br>
<br>
Example:<br>
Input 1:<br>
4<br>
Output 1:<br>
`
[[1 1 1 1]
[1 0 0 1]
[1 0 0 1]
[1 1 1 1]]
`<br>
Input 2:<br>
2<br>
Output 2:<br>
`
[[1 1] 
 [1 1]] 
`
<br>
Execution Time Limit<br>
5 seconds<br>

In [40]:
# Read the variable from STDIN
n = int(input())

import numpy as np
if n < 1:
    print()
elif n== 1:
    print([[1]])
if n > 1:
    a = np.zeros((n-2, n-2), dtype=np.int)
    c = np.ones((n-2, 1), dtype=np.int)
    r = np.ones((1,n), dtype=np.int)
    a = np.hstack((c, a, c))
    a = np.vstack((r, a, r))
    print(a)

10
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
